// <auto-generated />
using System;
using MesaDeAyuda.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MesaDeAyuda.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006032526_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MesaDeAyuda.Api.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TecnicoAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("TecnicoAsignadoId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("MesaDeAyuda.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@mesadeayuda.local",
                            Nombre = "Administrador",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Email = "tecnico1@mesadeayuda.local",
                            Nombre = "Técnico Soporte 1",
                            Rol = "Tecnico"
                        },
                        new
                        {
                            Id = 3,
                            Email = "tecnico2@mesadeayuda.local",
                            Nombre = "Técnico Soporte 2",
                            Rol = "Tecnico"
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Api.Models.Incidencia", b =>
                {
                    b.HasOne("MesaDeAyuda.Api.Models.Usuario", "TecnicoAsignado")
                        .WithMany("IncidenciasAsignadas")
                        .HasForeignKey("TecnicoAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TecnicoAsignado");
                });

            modelBuilder.Entity("MesaDeAyuda.Api.Models.Usuario", b =>
                {
                    b.Navigation("IncidenciasAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
